"""sync schema to v2.10

Revision ID: 24a092f3159a
Revises: 
Create Date: 2026-05-21 18:50:31.162102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a092f3159a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_app_stages_type_name'), 'app_stages', type_='unique')
    op.create_index(op.f('ix_contact_attachments_id'), 'contact_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_contact_notes_id'), 'contact_notes', ['id'], unique=False)
    op.create_index(op.f('ix_contact_tasks_id'), 'contact_tasks', ['id'], unique=False)
    op.alter_column('orders', 'gross_commission_rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.create_index(op.f('ix_pipeline_notes_id'), 'pipeline_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_notes_id'), table_name='pipeline_notes')
    op.alter_column('orders', 'gross_commission_rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_contact_tasks_id'), table_name='contact_tasks')
    op.drop_index(op.f('ix_contact_notes_id'), table_name='contact_notes')
    op.drop_index(op.f('ix_contact_attachments_id'), table_name='contact_attachments')
    op.create_unique_constraint(op.f('uq_app_stages_type_name'), 'app_stages', ['stage_type', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
